Job ID: 29458277
Algorithm: ppo
Erlang start: 50
Erlang stop: 150
Extra parameters: 
Timestamp: 2025-03-05_17-43-46
-------------------------
Beginning training process for the PATH AGENT using the Ppo algorithm.
Simulation started for Erlang: 50.0 simulation number: s1.
Traceback (most recent call last):
  File "/work/pi_vinod_vokkarane_uml_edu/git/FUSION/run_rl_sim.py", line 29, in <module>
    run_rl_sim()
  File "/work/pi_vinod_vokkarane_uml_edu/git/FUSION/run_rl_sim.py", line 19, in run_rl_sim
    run(env=env, sim_dict=sim_dict, callback_obj=callback_obj)
  File "/work/pi_vinod_vokkarane_uml_edu/git/FUSION/reinforcement_learning/workflow_runner.py", line 139, in run
    sum_returns = run_iters(env=env, sim_dict=sim_dict, is_training=True,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/pi_vinod_vokkarane_uml_edu/git/FUSION/reinforcement_learning/workflow_runner.py", line 65, in run_iters
    _run_drl_training(env=env, sim_dict=sim_dict)
  File "/work/pi_vinod_vokkarane_uml_edu/git/FUSION/reinforcement_learning/workflow_runner.py", line 29, in _run_drl_training
    model, yaml_dict = get_model(sim_dict=sim_dict, device=sim_dict['device'], env=env)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/pi_vinod_vokkarane_uml_edu/git/FUSION/reinforcement_learning/model_manager.py", line 26, in get_model
    model = ALGORITHM_REGISTRY[algorithm]['setup'](env=env, device=device)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/pi_vinod_vokkarane_uml_edu/git/FUSION/reinforcement_learning/utils/setup.py", line 44, in setup_ppo
    env_name = list(yaml_dict.keys())[0]
                    ^^^^^^^^^^^^^^
AttributeError: 'ScannerError' object has no attribute 'keys'
Error running Python script for algorithm ppo
-------------------------
Finished simulation for ppo with Erlang range 50 to 150
Output saved to slurm_logs/ppo/50/slurm_output_2025-03-05_17-43-46.out
